name: zoom-video-sdk
services:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: ianmubangizi/zoom.video.sdk
  name: zoom-video-sdk